### ISSUE TITLE
Null Reference Exception in ConceptPage.json.cs

### ISSUE THREAD

**Issue by threezool** [StarcounterPrefabs/Images#66]
### Steps to reproduce
Followed the tutorial and on step 8 (Mapper app for Images) when starting the app i get a Null Referenser Exception on line 18 in ConceptPage.json.cs.

Tried to run it both thru the app warehouse and clone the project with same result. Running the projects i used Visual Studio 2015 Community and started them both by letting Visual studio start them in order by setting it up in the solution properties and manually starting them by right clicking and choosing Debug -> New instance.

### Expected result
Getting a session id from the main project.

### Actual result
Null Reference Exception

##### Starcounter version 
Starcounter-Release-2.2.1.3234

##### Involved apps' version
StarcounterPrefabs/Images@eab600f0b01f0e36781b521bdb1ed1c061ac36a7
 
##### Browsers affected
- [x] Chrome

**Comment by warpech** [comment]
Thanks for reporting. Can you please paste the full stack trace that you get? It should be available in Starcounter Administrator > Log

**Comment by mmnosek** [comment]
Please check if #68 does not fix it.

**Comment by aloscha** [comment]
I'm pretty sure that #68 and #67 fixed the problem

**Comment by threezool** [comment]
Did another pass and this time with the Develop branch instead of the warehouse version and i still get a exception at line 18 in ConceptPage.json.cs.

Here is the complete stack trace:

   at Images.ConceptPage.OnData() in C:\Users\three\Documents\Visual Studio 2015\Projects\Starcounter Prefabs\Images\src\Images\ViewModels\ConceptPage.json.cs:line 18
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter\TransactionManager.cs:line 471
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Images.ConceptPage.set_Data(Something value)
   at Images.MainHandlers.<>c__DisplayClass3_1.<RegisterPartials>b__4() in C:\Users\three\Documents\Visual Studio 2015\Projects\Starcounter Prefabs\Images\src\Images\Api\MainHandlers.cs:line 104
   at Starcounter.Db.<>c__DisplayClass47_0`1.<Scope>b__0() in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter\Db.cs:line 428
   at Starcounter.Db.Scope(Action action, Boolean isReadOnly) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter\Db.cs:line 403
   at Starcounter.Db.Scope[TResult](Func`1 func, Boolean isReadOnly) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter\Db.cs:line 428
   at Images.MainHandlers.<>c.<RegisterPartials>b__3_3(String objectId) in C:\Users\three\Documents\Visual Studio 2015\Projects\Starcounter Prefabs\Images\src\Images\Api\MainHandlers.cs:line 102
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1117
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Internal\Rest\Self.cs:line 397
   at Starcounter.Self.GET(String uri) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Internal\Rest\Self.cs:line 74
   at StarcounterTutorialMapper.Program.<>c.<Main>b__0_1(String objectId) in C:\Users\three\Documents\Visual Studio 2015\Projects\StarcounterTutorial\StarcounterTutorialMapper\Program.cs:line 15
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1117
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Internal\Rest\Self.cs:line 397
   at Starcounter.Self.GET(UInt16 port, String uri, Dictionary`2 headersDictionary, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Internal\Rest\Self.cs:line 133
   at Starcounter.UriMapping.<>c__DisplayClass18_0.<CallAllHandlersForClass>b__0(HandlerInfoForUriMapping x) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 833
   at Starcounter.UriMapping.CallAllHandlersForClass(List`1 resps, MappingClassInfo type, String stringParam, List`1 alreadyCalledHandlers) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 850
   at Starcounter.UriMapping.CallAllHandlersInTypeHierarchy(Request req, String className, String paramStr, Boolean alreadyHasResponse) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 737
   at Starcounter.UriMapping.ClassHierarchyCallProxy(Request req, String className, String paramStr) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 930
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 161
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1117
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Internal\Rest\Self.cs:line 397
   at Starcounter.Self.GET(UInt16 port, String uri, Dictionary`2 headersDictionary, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Internal\Rest\Self.cs:line 133
   at Starcounter.UriMapping.<>c__DisplayClass14_0.<OntologyMap>b__0(Request req, String appObjectId) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 604
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 161
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1117
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Internal\Rest\Self.cs:line 397
   at Starcounter.Self.GET(String uri) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Internal\Rest\Self.cs:line 74
   at StarcounterTutorial.ViewModels.PersonPage.AddExpense(Expense expense) in C:\Users\three\Documents\Visual Studio 2015\Projects\StarcounterTutorial\StarcounterTutorial\ViewModels\PersonPage.json.cs:line 40
   at StarcounterTutorial.ViewModels.PersonPage.RefreshExpenses(IEnumerable`1 expenses) in C:\Users\three\Documents\Visual Studio 2015\Projects\StarcounterTutorial\StarcounterTutorial\ViewModels\PersonPage.json.cs:line 49
   at StarcounterTutorial.Program.<>c.<Main>b__0_1() in C:\Users\three\Documents\Visual Studio 2015\Projects\StarcounterTutorial\StarcounterTutorial\Program.cs:line 40
   at Starcounter.Db.<>c__DisplayClass47_0`1.<Scope>b__0() in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter\Db.cs:line 428
   at Starcounter.Db.Scope(Action action, Boolean isReadOnly) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter\Db.cs:line 403
   at Starcounter.Db.Scope[TResult](Func`1 func, Boolean isReadOnly) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter\Db.cs:line 428
   at StarcounterTutorial.Program.<>c.<Main>b__0_0() in C:\Users\three\Documents\Visual Studio 2015\Projects\StarcounterTutorial\StarcounterTutorial\Program.cs:line 17
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765

**Comment by threezool** [comment]
Updated the tutorial code to match the changes to the develop branch and it now works.

**Comment by aloscha** [comment]
Yeah in https://docs.starcounter.io/tutorial/mapper-app-for-images/ we have `/images/partials/concept/`, now we don't use the concept anymore but `content` or `illustration-edit`.
